apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-service
  description: Documentação do Payment Service
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: devops
